p_paths = {"videodownloader": "C:\\Program Files\\4KDownload\\4kvideodownloader\\4kvideodownloader.exe",
 "androidstudio": "C:\\Program Files\\Android\\Android Studio\\bin\\studio64.exe" ,
 "anydesk" : "C:\\Program Files (x86)\\AnyDesk\\AnyDesk.exe" ,
 "alexa" : "C:\\Program Files\\WindowsApps\\57540AMZNMobileLLC.AmazonAlexa_3.11.1285.0_x64__22t9g3sebte08\\Alexa.exe" ,
 "blender" : "C:\\Program Files\\WindowsApps\\BlenderFoundation.Blender_3.0.0.0_x64__ppwjx1n5r4v9t\Blender\\blender.exe" ,
 "bluestack" : "C:\\Program Files\\BlueStacks_nxt\\HD-Player.exe" ,
 "discord" : "C:\\Users\\Admin\\AppData\\Local\\Discord\\app-1.0.9003\\Discord.exe" ,
 "drivereasy" : "C:\\Program Files\\Easeware\\DriverEasy\\DriverEasy.exe" ,
 "epicgames" : "C:\\Program Files (x86)\\Epic Games\\Launcher\\Portal\\Binaries\\Win64\\EpicGamesLauncher.exe" ,
 "excel" : "C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE" ,
 "explorer" : "C:\\Windows\\explorer.exe" ,
 "powerpoint" : "C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE" ,
 "onenote" : "C:\\Program Files\\Microsoft Office\\root\\Office16\\ONENOTE.EXE" ,
 "firefox" : "C:\\Program Files\\Mozilla Firefox\\firefox.exe" ,
 "geforceexperience" : "C:\\Program Files\\NVIDIA Corporation\\NVIDIA GeForce Experience\\NVIDIA GeForce Experience.exe" ,
 "githubdesktop" : "C:\\Users\\Admin\\AppData\\Local\\GitHubDesktop\\GitHubDesktop.exe" ,
 "chrome" : "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" ,
 "grammarly" : "C:\\Users\\Admin\\AppData\\Local\\Grammarly\\DesktopIntegrations\\Grammarly.Desktop.exe" ,
 "python" : "C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python310\\python.exe" ,
 "malwarebytes" : "C:\\Program Files\\Malwarebytes\\Anti-Malware\\mbam.exe" ,
 "micorsoftedge" : "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe" ,
 "msiafterburner" : "C:\\Program Files (x86)\\MSI Afterburner\\MSIAfterburner.exe" ,
 "obsstudio" : "C:\\Program Files\\obs-studio\\bin\\64bit\\obs64.exe" ,
 "protonvpn" : "C:\\Program Files (x86)\\Proton Technologies\\ProtonVPN\\ProtonVPN.exe" ,
 "pycharm" : "C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.3\\bin\\pycharm64.exe" ,
 "qtdesigner" : "C:\\Program Files (x86)\\Qt Designer\\designer.exe" ,
 "visualstudio" : "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe" ,
 "steam" : "C:\\Program Files (x86)\\Steam\\steam.exe" ,
 "systeminfo" : "C:\\Windows\\system32\\msinfo32.exe" ,
 "tlauncher" : "C:\\Users\Admin\\AppData\\Roaming\\.minecraft\\TLauncher.exe" ,
 "typingmaster" : "C:\\Program Files (x86)\\TypingMaster11\\TypingMaster.exe" ,
 "ubisoftconnect" : "C:\\Program Files (x86)\\Ubisoft\\Ubisoft Game Launcher\\UbisoftConnect.exe" ,
 "vscode" : "C:\\Users\\Admin\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" ,
 "wondershare" : "C:\Program Files (x86)\Wondershare\Wondershare Filmora\\Wondershare Filmora X.exe" ,
 "utorrent" : "C:\\Users\\Admin\\AppData\\Roaming\\uTorrent\\uTorrent.exe" ,
 }